language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: lTazxyo0uiGyFiODhTaYBKJF90nJb4I+V91uxO1RSEkiBC32DWlhRSbmDfndUuTl8dPQNu5aujAjFwKh/iAu9j1u3cS/TZswx/nA1pIXFiZ9CLQ74tXClo8OhFqIl/6k5x0Qp87aQcnggc76LWOA6NSJ09Hvkgm77McjG/sm4tin1AVqZEP5R2mgdhn3lhz95Kx5P28VLZpMH/ElibHp5kjSpogzL8IqVsziU3zmyQS7zWZQKAhUyVJLiQWOlzLQ76IJnnISUV+OSEGHUTCE+Btv+Bd5IKA7euKAHz5l5pKSKVYPoKG1at5u+OecLVm29+KO85Ng7CuftFrz92mI9Lwl3V2bqB4gdC4DV1cQyLn844LwhjSo/eSmgwRWfGUXC2bsjJcY1hUQJcGsbi5Z8GyxgF32a5X36lT4jSF29cIvh+7CUpwoKj303luDEMfha4l76BrtEPZgc0+7uuBgHz4K3JHusT6yJSmuvfKArKYu0KG4ES4mUOKeX54XEmbsRzn8vdN+k14R/5Inz0+n6W86ANE3lBxzmCXtyjDQQMJHaF/1XYi69krrfIFxFLejNuEUVO8MI+yfiuEVLnu0SjCNbhgnMwu8E6pjEQwlO0favYd0R94shkn2xi6sGFiJun/vu8C65WBaZ2r5eg50p7yfKzMJl6/NX8tvWo6tVyw=
